# Generated by Django 5.2.5 on 2026-04-08 01:17

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Platform Administrator',
                'verbose_name_plural': '03. Staff & Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GuestUser',
            fields=[
            ],
            options={
                'verbose_name': 'Guest User (Lead)',
                'verbose_name_plural': '01. Guest Users (Leads)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
            ],
            options={
                'verbose_name': 'Student User',
                'verbose_name_plural': '02. Paid Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Platform Superuser'), ('SCHOOL_ADMIN', 'School Admin'), ('STUDENT', 'Paid Student'), ('GUEST', 'Guest Visitor')], default='GUEST', max_length=20),
        ),
    ]
