# Generated by Django 5.2.5 on 2026-04-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_serviceinquiry_is_paid_serviceinquiry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinquiry',
            name='background',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Educational/Clinical Background'),
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='current_job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Job/Status'),
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='language_goal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='German Language/Career Goal'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='service_requested',
            field=models.CharField(choices=[('DEEP_ANALYSIS', 'Direct Career Consultation'), ('FOLLOW_UP', 'Follow Up Session'), ('CV_LETTER', 'CV & Motivation Letter'), ('CHECKLIST', 'Personalized Checklist'), ('PROGRAM', 'Full German Training Program'), ('EXPLORING', 'Just Exploring / Passing By')], max_length=50),
        ),
    ]
