# Generated by Django 5.2.5 on 2026-04-06 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_serviceinquiry_background_serviceinquiry_current_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinquiry',
            name='service_requested',
            field=models.CharField(choices=[('DEEP_ANALYSIS', 'Direct Career Consultation'), ('FOLLOW_UP', 'Follow Up Session'), ('CV_LETTER', 'CV & Motivation Letter'), ('CHECKLIST', 'Personalized Checklist'), ('PROGRAM', 'Full German Training Program'), ('EXPLORING', 'Just Exploring / Passing By'), ('ENROLL_BASIC', 'German Career: Basic (₱12,000)'), ('ENROLL_STANDARD', 'German Career: Standard (₱15,000)'), ('ENROLL_PREMIUM', 'German Career: Premium (₱20,000)')], max_length=50),
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_hero_title', models.CharField(default='The future of Filipino Healthcare Careers in Europe', max_length=255)),
                ('home_hero_subtitle', models.CharField(default='Step into your German career with confidence.', max_length=255)),
                ('home_hero_cta', models.CharField(default='Our Language Programs', max_length=100)),
                ('home_about_title', models.CharField(default='The European Dream is closer than you think.', max_length=255)),
                ('home_about_text', models.TextField(default='We bridge the gap between talented healthcare professionals and premium opportunities in Germany. Our holistic approach combines language mastery, cultural integration, and professional placement.')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_settings', to='core.school')),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
