# Generated by Django 5.2.5 on 2026-04-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_serviceinquiry_service_requested_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteSettings',
        ),
    ]
