# Generated by Django 5.2.5 on 2026-03-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ENROLLED', 'Enrolled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12),
        ),
    ]
