# Generated by Django 5.2.5 on 2026-04-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_courseenrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('GEN', 'General German'), ('MED', 'Medical German'), ('BUS', 'Business German'), ('EXM', 'Exam Preparation')], default='GEN', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
    ]
