# Generated by Django 5.2.5 on 2026-04-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_course_category_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('LANG', 'Language Course'), ('LMS', 'LMS'), ('EXM', 'Exam Preparation Course'), ('OTH', 'Others')], default='LANG', max_length=4),
        ),
    ]
