# Generated by Django 5.2.5 on 2026-04-08 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('ASN', 'Assignment/Submission'), ('INT', 'Interactive Task'), ('REF', 'Reflection/Journal'), ('PRC', 'Practice Session')], default='PRC', max_length=3)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='learning.lesson')),
            ],
            options={
                'verbose_name_plural': 'Lesson Activities',
                'ordering': ['order'],
            },
        ),
    ]
