# Generated by Django 5.2.5 on 2026-04-08 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_lessonactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True, help_text='Text-based answer or reflection')),
                ('submission_file', models.FileField(blank=True, help_text='Supports Audio (MP3/WAV), PDF, or Images', null=True, upload_to='activity_submissions/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('GRADED', 'Graded/Reviewed'), ('RESUBMIT', 'Requires Resubmission')], default='PENDING', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.lessonactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
