# Generated by Django 5.2.5 on 2026-04-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_activitysubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='submission_url',
            field=models.URLField(blank=True, help_text='Link to external work (e.g., Google Drive, Dropbox)', null=True),
        ),
    ]
