# Generated by Django 5.2.5 on 2026-04-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_activitysubmission_submission_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Time limit in minutes (for quizzes/exams).'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_final_exam',
            field=models.BooleanField(default=False, help_text='If true, this quiz acts as the course completion exam.'),
        ),
    ]
