# Generated by Django 5.2.5 on 2026-07-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='quiz_audio/'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
