# Generated by Django 6.1 on 2026-08-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_coursetier_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_in_catalog',
            field=models.BooleanField(default=True, help_text='Show this course in the public/school course catalog for non-enrolled students'),
        ),
    ]
