# Generated by Django 6.1 on 2026-08-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_course_show_in_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Custom message from admin regarding this enrollment status', null=True),
        ),
    ]
