# Generated by Django 6.1 on 2026-08-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_courseenrollment_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='proof_note',
            field=models.TextField(blank=True, help_text='Wise transaction reference code or student note'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='provider',
            field=models.CharField(default='wise', max_length=20),
        ),
    ]
