# Generated by Django 5.2.5 on 2026-03-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('DIY', 'DIY Guide'), ('ART', 'Article'), ('NEWS', 'News & Updates')], default='ART', max_length=5)),
                ('excerpt', models.TextField(help_text='Short summary shown on the list page')),
                ('content', models.TextField(help_text='Full post body (HTML or plain text)')),
                ('cover_emoji', models.CharField(default='📄', help_text='Emoji used as cover art', max_length=10)),
                ('author', models.CharField(default='PME Consulting EU', max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
