# Generated by Django 5.2.5 on 2026-04-06 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_serviceinquiry_service_requested_and_more'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_posts', to='core.school'),
        ),
    ]
