# Generated by Django 5.2.5 on 2026-04-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_post_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='school',
        ),
    ]
